//! Admin panel theme system JavaScript.
//!
//! Extracted from static/admin/core.js (theme system section).
//! Contains: color math (HSL), theme loading/persistence, theme picker UI,
//! theme customizer with live preview, AI theme panel, export/import.
//!
//! This JS is injected into the admin page via CmsModule::admin_js().
//! It expects these globals from core.js: toast(), esc()
//! It provides these globals: liqLoadThemes(), liqApplyTheme(),
//!   renderThemePicker(), renderThemeCustomizer(), renderAiThemePanel()
//!
//! Related: dashboard_themes/mod.rs (theme data), ab_testing (theme experiments)

/// Returns the complete theme system JavaScript as a string.
pub fn theme_system_js() -> String {
    THEME_SYSTEM_JS.to_string()
}

const THEME_SYSTEM_JS: &str = r####"
// ── Admin Theme System ──────────────────────────────────────────
// Generated by: src/modules/dashboard_themes/admin_js.rs
// Extracted from: static/admin/core.js (theme system section)
// Related: theme_studio/admin.rs (site design tokens), ab_testing (experiments)
// Provides: liqLoadThemes, liqApplyTheme, renderThemePicker, renderThemeCustomizer

// ── Theme system (global) ───────────────────────────────────────────
var _liqThemesCache = null;
var _liqCustomThemes = JSON.parse(localStorage.getItem('liq-custom-themes') || '[]');

function liqLoadThemes() {
    if (_liqThemesCache) return Promise.resolve(_liqThemesCache);
    return fetch('/api/modules/dashboard/themes')
        .then(function(r) { return r.json(); })
        .then(function(res) {
            if (res.ok && res.data) {
                _liqThemesCache = res.data;
                return res.data;
            }
            return [];
        })
        .catch(function() { return []; });
}

function liqAllThemes() {
    var base = _liqThemesCache || [];
    return base.concat(_liqCustomThemes);
}

function liqParseThemeColor(value) {
    if (!value) return null;
    var raw = String(value).trim();
    var hex = raw.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
    if (hex) {
        var body = hex[1];
        if (body.length === 3) {
            body = body.split('').map(function(ch) { return ch + ch; }).join('');
        }
        return {
            r: parseInt(body.slice(0, 2), 16),
            g: parseInt(body.slice(2, 4), 16),
            b: parseInt(body.slice(4, 6), 16),
        };
    }
    var rgb = raw.match(/^rgba?\(([^)]+)\)$/i);
    if (rgb) {
        var parts = rgb[1].split(',').map(function(part) { return parseFloat(part.trim()); });
        if (parts.length >= 3 && parts.every(function(part, idx) { return idx > 2 || isFinite(part); })) {
            return { r: parts[0], g: parts[1], b: parts[2] };
        }
    }
    return null;
}

function liqAccentInk(accent, isLight) {
    var rgb = liqParseThemeColor(accent);
    if (!rgb) return isLight ? '#0f172a' : '#ffffff';
    var luminance = ((0.299 * rgb.r) + (0.587 * rgb.g) + (0.114 * rgb.b)) / 255;
    return luminance > 0.62 ? '#0f172a' : '#ffffff';
}

function liqAugmentThemeCss(css, isLight) {
    var source = String(css || '');
    var accentMatch = source.match(/--accent:\s*([^;]+);/i);
    var ink = liqAccentInk(accentMatch ? accentMatch[1].trim() : '', isLight);

    // Enforce minimum contrast for nav text against surface background.
    // If --text-muted is too close to --surface, auto-derive a readable alternative.
    var surfaceMatch = source.match(/--surface:\s*([^;]+);/i);
    var textMatch = source.match(/--text:\s*([^;]+);/i);
    var mutedMatch = source.match(/--text-muted:\s*([^;]+);/i);
    var navFix = '';
    if (surfaceMatch) {
        var surfRgb = liqParseThemeColor(surfaceMatch[1].trim());
        if (surfRgb) {
            var surfLum = ((0.299 * surfRgb.r) + (0.587 * surfRgb.g) + (0.114 * surfRgb.b)) / 255;
            // Check --text-muted contrast
            if (mutedMatch) {
                var mutedRgb = liqParseThemeColor(mutedMatch[1].trim());
                if (mutedRgb) {
                    var mutedLum = ((0.299 * mutedRgb.r) + (0.587 * mutedRgb.g) + (0.114 * mutedRgb.b)) / 255;
                    var contrast = Math.abs(surfLum - mutedLum);
                    if (contrast < 0.3) {
                        // Override --text-muted for sufficient contrast
                        navFix = surfLum > 0.5
                            ? ' --text-muted: #475569; --text: #0f172a;'
                            : ' --text-muted: #94a3b8; --text: #f1f5f9;';
                    }
                }
            }
            // Also check --text
            if (textMatch) {
                var textRgb = liqParseThemeColor(textMatch[1].trim());
                if (textRgb) {
                    var textLum = ((0.299 * textRgb.r) + (0.587 * textRgb.g) + (0.114 * textRgb.b)) / 255;
                    var textContrast = Math.abs(surfLum - textLum);
                    if (textContrast < 0.25) {
                        navFix += surfLum > 0.5 ? ' --text: #0f172a;' : ' --text: #f1f5f9;';
                    }
                }
            }
        }
    }

    var extra = '--accent-ink: ' + ink + ';' + navFix;
    if (/--accent-ink:/i.test(source)) {
        source = source.replace(/--accent-ink:\s*[^;]+;/i, extra);
        return source;
    }
    return source + '\n:root { ' + extra + ' }';
}

function liqApplyTheme(themeId, themes) {
    var el = document.getElementById('liq-theme');
    if (!el) {
        el = document.createElement('style');
        el.id = 'liq-theme';
        document.head.appendChild(el);
    }
    var css = '';
    var isLight = false;
    var all = themes ? themes.concat(_liqCustomThemes) : _liqCustomThemes;
    for (var i = 0; i < all.length; i++) {
        if (all[i].id === themeId) {
            css = all[i].css;
            isLight = !!all[i].light;
            break;
        }
    }
    css = liqAugmentThemeCss(css, isLight);
    el.textContent = css;
    localStorage.setItem('liq-theme-css', css);
    localStorage.setItem('liq-theme-id', themeId);
    // A/B testing hook: track admin theme preference
    if (window.dispatchEvent) {
        window.dispatchEvent(new CustomEvent('liq:ab-event', {
            detail: { event: 'admin_theme_applied', variant: themeId }
        }));
    }
    // Toggle light theme body class
    if (isLight) {
        document.body.classList.add('liq-light');
    } else {
        document.body.classList.remove('liq-light');
    }
}

function liqApplyCustomCss(cssVarsObj, isLight) {
    var parts = [];
    var varMap = { bg:'--bg', surface:'--surface', surface2:'--surface2', border:'--border',
        text:'--text', text_muted:'--text-muted', accent:'--accent', accent_hover:'--accent-hover',
        success:'--success', danger:'--danger', warning:'--warning' };
    for (var k in varMap) {
        if (cssVarsObj[k]) parts.push(varMap[k] + ': ' + cssVarsObj[k]);
    }
    var css = ':root { ' + parts.join('; ') + ' }';
    css = liqAugmentThemeCss(css, isLight);
    var el = document.getElementById('liq-theme');
    if (!el) { el = document.createElement('style'); el.id = 'liq-theme'; document.head.appendChild(el); }
    el.textContent = css;
    localStorage.setItem('liq-theme-css', css);
    localStorage.setItem('liq-theme-id', 'custom');
    if (isLight) document.body.classList.add('liq-light');
    else document.body.classList.remove('liq-light');
    return css;
}

function liqSaveCustomTheme(name, cssVarsObj, isLight) {
    var id = 'custom-' + Date.now();
    var parts = [];
    var varMap = { bg:'--bg', surface:'--surface', surface2:'--surface2', border:'--border',
        text:'--text', text_muted:'--text-muted', accent:'--accent', accent_hover:'--accent-hover',
        success:'--success', danger:'--danger', warning:'--warning' };
    for (var k in varMap) {
        if (cssVarsObj[k]) parts.push(varMap[k] + ': ' + cssVarsObj[k]);
    }
    var theme = {
        id: id, name: name, description: 'Custom theme', light: !!isLight,
        css: ':root { ' + parts.join('; ') + ' }',
        accent: cssVarsObj.accent || '#3b82f6', bg: cssVarsObj.bg || '#0f172a',
        css_vars: cssVarsObj
    };
    _liqCustomThemes.push(theme);
    localStorage.setItem('liq-custom-themes', JSON.stringify(_liqCustomThemes));
    return theme;
}

function liqDeleteCustomTheme(themeId) {
    _liqCustomThemes = _liqCustomThemes.filter(function(t) { return t.id !== themeId; });
    localStorage.setItem('liq-custom-themes', JSON.stringify(_liqCustomThemes));
}

/* Load saved theme on page load — localStorage is authoritative, server is fallback */
(function() {
    var localId = localStorage.getItem('liq-theme-id');
    var cached = localStorage.getItem('liq-theme-css');
    // Reuse the existing <style id="liq-theme"> from the HTML template (never create a second one)
    var el = document.getElementById('liq-theme');
    if (!el) {
        el = document.createElement('style'); el.id = 'liq-theme';
        document.head.appendChild(el);
    }
    // Apply cached CSS immediately to prevent flash
    if (cached) {
        el.textContent = cached;
        // Check light status
        var isLight = false;
        var all = (_liqThemesCache || []).concat(_liqCustomThemes);
        for (var i = 0; i < all.length; i++) {
            if (all[i].id === localId) { isLight = !!all[i].light; break; }
        }
        if (isLight) document.body.classList.add('liq-light');
    }
    // Sync with server — only use server value if we have nothing locally
    if (localId) {
        // We have a local choice — ensure it's applied with full theme data
        liqLoadThemes().then(function(themes) {
            liqApplyTheme(localId, themes);
        });
        // Still fetch server layout if we don't have one locally
        if (!localStorage.getItem('liq-dash-layout')) {
            fetch('/api/modules/dashboard/theme')
                .then(function(r) { return r.json(); })
                .then(function(res) {
                    if (res.ok && res.data && res.data.layout) {
                        localStorage.setItem('liq-dash-layout', JSON.stringify(res.data.layout));
                    }
                })
                .catch(function() {});
        }
    } else {
        // Fresh browser — fetch from server
        fetch('/api/modules/dashboard/theme')
            .then(function(r) { return r.json(); })
            .then(function(res) {
                if (res.ok && res.data) {
                    liqLoadThemes().then(function(themes) {
                        liqApplyTheme(res.data.theme, themes);
                    });
                    if (res.data.layout) {
                        localStorage.setItem('liq-dash-layout', JSON.stringify(res.data.layout));
                    }
                }
            })
            .catch(function() {});
    }
})();

/* ── Theme Picker ────────────────────────────────────────────────────── */
function renderThemePicker(parent, themes) {
    if (!themes || !themes.length) return;

    // Remove any existing picker in this parent (prevents duplicates on re-render)
    var old = parent.querySelector('.theme-picker-wrap');
    if (old) old.remove();

    var all = themes.concat(_liqCustomThemes);
    var wrap = document.createElement('div');
    wrap.className = 'theme-picker-wrap';

    /* Top row: label + select + swatch + description */
    var topRow = document.createElement('div');
    topRow.className = 'theme-picker-row';

    var lbl = document.createElement('label');
    lbl.textContent = 'Theme';
    topRow.appendChild(lbl);

    var sel = document.createElement('select');
    sel.className = 'theme-picker-select';

    var currentId = localStorage.getItem('liq-theme-id') || 'azle';

    for (var i = 0; i < all.length; i++) {
        var t = all[i];
        var opt = document.createElement('option');
        opt.value = t.id;
        opt.textContent = (t.id.indexOf('custom-') === 0 ? '\u2605 ' : '') + t.name;
        if (t.id === currentId) opt.selected = true;
        sel.appendChild(opt);
    }
    topRow.appendChild(sel);

    /* Swatch preview */
    var swatch = document.createElement('span');
    swatch.className = 'theme-swatch';
    updateSwatch(swatch, all, currentId);
    topRow.appendChild(swatch);

    /* Description */
    var desc = document.createElement('span');
    desc.className = 'theme-picker-desc';
    updateDesc(desc, all, currentId);
    topRow.appendChild(desc);

    wrap.appendChild(topRow);

    /* Button row: Customize, AI Generate, Export, Import */
    var btnRow = document.createElement('div');
    btnRow.className = 'theme-picker-buttons';

    /* Customize button */
    var custBtn = document.createElement('button');
    custBtn.className = 'btn btn-ghost btn-sm';
    custBtn.textContent = 'Customize';
    custBtn.onclick = function() { renderThemeCustomizer(parent, themes); };
    btnRow.appendChild(custBtn);

    /* AI Generate button */
    var aiBtn = document.createElement('button');
    aiBtn.className = 'btn btn-primary btn-sm';
    aiBtn.textContent = 'AI Generate';
    aiBtn.onclick = function() { renderAiThemePanel(parent, themes); };
    btnRow.appendChild(aiBtn);

    /* Export / Import buttons */
    var expBtn = document.createElement('button');
    expBtn.className = 'btn btn-ghost btn-sm';
    expBtn.textContent = 'Export';
    expBtn.onclick = function() { liqExportTheme(all, sel.value); };
    btnRow.appendChild(expBtn);

    var impBtn = document.createElement('button');
    impBtn.className = 'btn btn-ghost btn-sm';
    impBtn.textContent = 'Import';
    impBtn.onclick = function() { liqImportTheme(themes); };
    btnRow.appendChild(impBtn);

    wrap.appendChild(btnRow);

    /* On change — use closure refs, not DOM lookups */
    sel.addEventListener('change', function() {
        var newId = sel.value;
        liqApplyTheme(newId, all);
        updateSwatch(swatch, all, newId);
        updateDesc(desc, all, newId);

        /* Save to server */
        var payload = (newId.indexOf('custom-') !== 0)
            ? { theme: newId }
            : { theme: 'custom', custom_name: newId };
        fetch('/api/modules/dashboard/theme', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        }).catch(function() {});
    });

    /* Insert after the header row (h2's container) or the h2 itself */
    var h2 = parent.querySelector('h2');
    var ref = h2 ? h2.parentNode : null;
    /* If h2 is inside a wrapper div (not main directly), insert after that wrapper */
    if (ref && ref !== parent) {
        if (ref.nextSibling) parent.insertBefore(wrap, ref.nextSibling);
        else parent.appendChild(wrap);
    } else if (h2 && h2.nextSibling) {
        parent.insertBefore(wrap, h2.nextSibling);
    } else {
        parent.appendChild(wrap);
    }
}

function updateSwatch(el, themes, id) {
    if (!el) return;
    for (var i = 0; i < themes.length; i++) {
        if (themes[i].id === id) {
            el.style.background = themes[i].accent;
            el.style.boxShadow = '0 0 0 3px ' + themes[i].bg;
            return;
        }
    }
}

function updateDesc(el, themes, id) {
    if (!el) return;
    for (var i = 0; i < themes.length; i++) {
        if (themes[i].id === id) {
            el.textContent = themes[i].description;
            return;
        }
    }
    el.textContent = '';
}

/* ── Color Math (HSL) for Lite auto-derive ────────────────────────────── */
function _liqHexToHsl(hex) {
    var r = parseInt(hex.slice(1,3), 16) / 255;
    var g = parseInt(hex.slice(3,5), 16) / 255;
    var b = parseInt(hex.slice(5,7), 16) / 255;
    var max = Math.max(r, g, b), min = Math.min(r, g, b);
    var h = 0, s = 0, l = (max + min) / 2;
    if (max !== min) {
        var d = max - min;
        s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        else if (max === g) h = ((b - r) / d + 2) / 6;
        else h = ((r - g) / d + 4) / 6;
    }
    return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)];
}

function _liqHslToHex(h, s, l) {
    h = ((h % 360) + 360) % 360;
    s = Math.max(0, Math.min(100, s)) / 100;
    l = Math.max(0, Math.min(100, l)) / 100;
    var c = (1 - Math.abs(2 * l - 1)) * s;
    var x = c * (1 - Math.abs((h / 60) % 2 - 1));
    var m = l - c / 2;
    var r = 0, g = 0, b = 0;
    if (h < 60) { r = c; g = x; }
    else if (h < 120) { r = x; g = c; }
    else if (h < 180) { g = c; b = x; }
    else if (h < 240) { g = x; b = c; }
    else if (h < 300) { r = x; b = c; }
    else { r = c; b = x; }
    var toHex = function(v) { var h = Math.round((v + m) * 255).toString(16); return h.length < 2 ? '0' + h : h; };
    return '#' + toHex(r) + toHex(g) + toHex(b);
}

function _liqLighten(hex, pct) {
    var hsl = _liqHexToHsl(hex);
    return _liqHslToHex(hsl[0], hsl[1], Math.min(100, hsl[2] + pct));
}

function _liqDarken(hex, pct) {
    var hsl = _liqHexToHsl(hex);
    return _liqHslToHex(hsl[0], hsl[1], Math.max(0, hsl[2] - pct));
}

function _liqBlendAlpha(fgHex, bgHex, alpha) {
    var fg = [parseInt(fgHex.slice(1,3),16), parseInt(fgHex.slice(3,5),16), parseInt(fgHex.slice(5,7),16)];
    var bg = [parseInt(bgHex.slice(1,3),16), parseInt(bgHex.slice(3,5),16), parseInt(bgHex.slice(5,7),16)];
    var toHex = function(v) { var h = Math.round(v).toString(16); return h.length < 2 ? '0' + h : h; };
    return '#' + toHex(fg[0]*alpha + bg[0]*(1-alpha)) + toHex(fg[1]*alpha + bg[1]*(1-alpha)) + toHex(fg[2]*alpha + bg[2]*(1-alpha));
}

function _liqShiftHue(hex, degrees) {
    var hsl = _liqHexToHsl(hex);
    return _liqHslToHex(hsl[0] + degrees, hsl[1], hsl[2]);
}

function _liqDeriveFullPalette(bg, text, accent, success, danger, isLight) {
    return {
        bg: bg,
        surface: isLight ? _liqDarken(bg, 3) : _liqLighten(bg, 4),
        surface2: isLight ? _liqDarken(bg, 6) : _liqLighten(bg, 7),
        border: isLight ? _liqDarken(bg, 10) : _liqLighten(bg, 10),
        text: text,
        text_muted: _liqBlendAlpha(text, bg, 0.6),
        accent: accent,
        accent_hover: _liqDarken(accent, 8),
        success: success,
        danger: danger,
        warning: _liqShiftHue(danger, 30)
    };
}

/* ── Theme Customizer ────────────────────────────────────────────────── */
function renderThemeCustomizer(parent, themes) {
    // Remove existing customizer/ai panels
    var existing = parent.querySelector('.theme-customizer');
    if (existing) { existing.remove(); return; } // toggle off
    var aiPanel = parent.querySelector('.ai-theme-panel');
    if (aiPanel) aiPanel.remove();

    var panel = document.createElement('div');
    panel.className = 'theme-customizer';

    // Determine tier: central/professional/enterprise = Pro; everything else = Lite
    var role = (window.__CMS && window.__CMS.nexusRole) || '';
    var isPro = role === 'central' || role === 'professional' || role === 'enterprise';

    var h3 = document.createElement('h3');
    h3.textContent = isPro ? 'Pro Theme Customizer' : 'Theme Customizer';
    if (!isPro) {
        var liteBadge = document.createElement('span');
        liteBadge.textContent = 'LITE';
        liteBadge.style.cssText = 'font-size:10px;font-weight:700;color:var(--text-muted);background:var(--surface2);padding:2px 6px;border-radius:4px;margin-left:8px;';
        h3.appendChild(liteBadge);
    }
    panel.appendChild(h3);

    // Name row
    var nameRow = document.createElement('div');
    nameRow.className = 'tc-row';
    var nameLbl = document.createElement('label');
    nameLbl.textContent = 'Name';
    nameRow.appendChild(nameLbl);
    var nameInput = document.createElement('input');
    nameInput.type = 'text';
    nameInput.placeholder = 'My Custom Theme';
    nameInput.value = '';
    nameRow.appendChild(nameInput);
    panel.appendChild(nameRow);

    // Start from row
    var startRow = document.createElement('div');
    startRow.className = 'tc-row';
    var startLbl = document.createElement('label');
    startLbl.textContent = 'Start from';
    startRow.appendChild(startLbl);
    var startSel = document.createElement('select');
    var allThemes = themes.concat(_liqCustomThemes);
    for (var i = 0; i < allThemes.length; i++) {
        var opt = document.createElement('option');
        opt.value = allThemes[i].id;
        opt.textContent = allThemes[i].name;
        startSel.appendChild(opt);
    }
    var curId = localStorage.getItem('liq-theme-id') || 'azle';
    startSel.value = curId;
    startRow.appendChild(startSel);

    // Light theme toggle
    var lightLbl = document.createElement('label');
    lightLbl.style.cssText = 'display:flex;align-items:center;gap:6px;font-size:13px;color:var(--text-muted);cursor:pointer;';
    var lightCb = document.createElement('input');
    lightCb.type = 'checkbox';
    lightLbl.appendChild(lightCb);
    lightLbl.appendChild(document.createTextNode('Light theme'));
    startRow.appendChild(lightLbl);
    panel.appendChild(startRow);

    // Define ALL 11 fields
    var allFields = [
        { key: 'bg',           label: 'Background',   cssVar: '--bg' },
        { key: 'surface',      label: 'Surface',       cssVar: '--surface' },
        { key: 'surface2',     label: 'Surface 2',     cssVar: '--surface2' },
        { key: 'border',       label: 'Border',        cssVar: '--border' },
        { key: 'text',         label: 'Text',          cssVar: '--text' },
        { key: 'text_muted',   label: 'Text Muted',    cssVar: '--text-muted' },
        { key: 'accent',       label: 'Accent',        cssVar: '--accent' },
        { key: 'accent_hover', label: 'Accent Hover',  cssVar: '--accent-hover' },
        { key: 'success',      label: 'Success',       cssVar: '--success' },
        { key: 'danger',       label: 'Danger',        cssVar: '--danger' },
        { key: 'warning',      label: 'Warning',       cssVar: '--warning' },
    ];

    // Lite gets 5 essential pickers; Pro gets all 11
    var liteKeys = ['bg', 'text', 'accent', 'success', 'danger'];
    var visibleFields = isPro ? allFields : allFields.filter(function(f) { return liteKeys.indexOf(f.key) >= 0; });

    if (!isPro) {
        var note = document.createElement('div');
        note.style.cssText = 'font-size:12px;color:var(--text-muted);margin-bottom:8px;';
        note.textContent = '5 essential colors \u2014 the rest are auto-calculated from these.';
        panel.appendChild(note);
    }

    var colorInputs = {};
    var hexLabels = {};
    var grid = document.createElement('div');
    grid.className = 'tc-grid';

    visibleFields.forEach(function(f) {
        var field = document.createElement('div');
        field.className = 'tc-field';
        var lbl = document.createElement('label');
        lbl.textContent = f.label;
        field.appendChild(lbl);
        var inp = document.createElement('input');
        inp.type = 'color';
        inp.value = '#888888';
        colorInputs[f.key] = inp;
        field.appendChild(inp);
        var hex = document.createElement('span');
        hex.className = 'tc-hex';
        hex.textContent = inp.value;
        hexLabels[f.key] = hex;
        field.appendChild(hex);
        grid.appendChild(field);

        inp.addEventListener('input', function() {
            hex.textContent = inp.value;
            previewColors();
        });
    });
    panel.appendChild(grid);

    // Pro sections (visible to both tiers — Lite can preview but not save)
    var proSections = document.createElement('div');
    proSections.className = 'tc-pro-sections';

    // --- Full Color Control (Lite only — Pro already has all 11) ---
    if (!isPro) {
        var colorSection = document.createElement('details');
        colorSection.className = 'tc-pro-section';
        var colorSummary = document.createElement('summary');
        var colorSummaryText = document.createTextNode('Full Color Control ');
        colorSummary.appendChild(colorSummaryText);
        var colorProBadge = document.createElement('span');
        colorProBadge.className = 'pro-badge';
        colorProBadge.textContent = 'PRO';
        colorSummary.appendChild(colorProBadge);
        colorSection.appendChild(colorSummary);
        var extraGrid = document.createElement('div');
        extraGrid.className = 'tc-grid';
        var extraKeys = allFields.filter(function(f) { return liteKeys.indexOf(f.key) < 0; });
        extraKeys.forEach(function(f) {
            var field = document.createElement('div');
            field.className = 'tc-field';
            var lbl = document.createElement('label');
            lbl.textContent = f.label;
            field.appendChild(lbl);
            var inp = document.createElement('input');
            inp.type = 'color';
            inp.value = '#888888';
            colorInputs[f.key] = inp;
            field.appendChild(inp);
            var hex = document.createElement('span');
            hex.className = 'tc-hex';
            hex.textContent = inp.value;
            hexLabels[f.key] = hex;
            field.appendChild(hex);
            extraGrid.appendChild(field);
            inp.addEventListener('input', function() {
                hex.textContent = inp.value;
                previewColors();
            });
        });
        colorSection.appendChild(extraGrid);
        proSections.appendChild(colorSection);
    }

    // --- Typography Section ---
    var typoSection = document.createElement('details');
    typoSection.className = 'tc-pro-section';
    var typoSummary = document.createElement('summary');
    var typoSummaryText = document.createTextNode('Typography');
    typoSummary.appendChild(typoSummaryText);
    if (!isPro) {
        var typoSummarySpace = document.createTextNode(' ');
        typoSummary.appendChild(typoSummarySpace);
        var typoProBadge = document.createElement('span');
        typoProBadge.className = 'pro-badge';
        typoProBadge.textContent = 'PRO';
        typoSummary.appendChild(typoProBadge);
    }
    typoSection.appendChild(typoSummary);
    var typoGrid = document.createElement('div');
    typoGrid.className = 'tc-grid tc-typography';

    var proInputs = {};

    // Font family
    var fontField = document.createElement('div');
    fontField.className = 'tc-field';
    var fontLbl = document.createElement('label'); fontLbl.textContent = 'Font Family';
    fontField.appendChild(fontLbl);
    var fontSel = document.createElement('select');
    proInputs.fontFamily = fontSel;
    var fonts = [
        { val: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', label: 'System Default' },
        { val: '"Inter", sans-serif', label: 'Inter' },
        { val: '"Roboto", sans-serif', label: 'Roboto' },
        { val: '"Open Sans", sans-serif', label: 'Open Sans' },
        { val: '"Lato", sans-serif', label: 'Lato' },
        { val: '"Poppins", sans-serif', label: 'Poppins' },
        { val: '"Source Sans Pro", sans-serif', label: 'Source Sans Pro' },
        { val: '"Nunito", sans-serif', label: 'Nunito' },
        { val: '"JetBrains Mono", monospace', label: 'JetBrains Mono' },
        { val: '"Georgia", serif', label: 'Georgia' },
    ];
    fonts.forEach(function(f) {
        var o = document.createElement('option'); o.value = f.val; o.textContent = f.label;
        fontSel.appendChild(o);
    });
    fontSel.addEventListener('change', function() {
        // Load Google Font if not system
        var val = fontSel.value;
        if (val.indexOf('-apple-system') < 0 && val.indexOf('Georgia') < 0) {
            var fontName = val.split('"')[1];
            if (fontName && !document.querySelector('link[data-gfont="' + fontName + '"]')) {
                var link = document.createElement('link');
                link.rel = 'stylesheet';
                link.href = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(fontName) + ':wght@300;400;500;600;700&display=swap';
                link.dataset.gfont = fontName;
                document.head.appendChild(link);
            }
        }
        previewProSettings();
    });
    fontField.appendChild(fontSel);
    typoGrid.appendChild(fontField);

    // Heading scale
    var hScaleField = document.createElement('div');
    hScaleField.className = 'tc-field';
    var hScaleLbl = document.createElement('label'); hScaleLbl.textContent = 'Heading Scale';
    hScaleField.appendChild(hScaleLbl);
    var hScaleSel = document.createElement('select');
    proInputs.headingScale = hScaleSel;
    [{ val: '0.85', label: 'Small' }, { val: '1', label: 'Default' }, { val: '1.15', label: 'Large' }].forEach(function(o) {
        var opt = document.createElement('option'); opt.value = o.val; opt.textContent = o.label;
        hScaleSel.appendChild(opt);
    });
    hScaleSel.value = '1';
    hScaleSel.addEventListener('change', previewProSettings);
    hScaleField.appendChild(hScaleSel);
    typoGrid.appendChild(hScaleField);

    // Body font size range
    var bsField = document.createElement('div');
    bsField.className = 'tc-field';
    var bsLbl = document.createElement('label'); bsLbl.textContent = 'Body Font Size';
    bsField.appendChild(bsLbl);
    var bsRange = document.createElement('input'); bsRange.type = 'range'; bsRange.min = '12'; bsRange.max = '16'; bsRange.value = '14'; bsRange.step = '1';
    proInputs.bodyFontSize = bsRange;
    var bsVal = document.createElement('span'); bsVal.className = 'tc-hex'; bsVal.textContent = '14px';
    bsRange.addEventListener('input', function() { bsVal.textContent = bsRange.value + 'px'; previewProSettings(); });
    bsField.appendChild(bsRange);
    bsField.appendChild(bsVal);
    typoGrid.appendChild(bsField);

    // Border radius range
    var brField = document.createElement('div');
    brField.className = 'tc-field';
    var brLbl = document.createElement('label'); brLbl.textContent = 'Border Radius';
    brField.appendChild(brLbl);
    var brRange = document.createElement('input'); brRange.type = 'range'; brRange.min = '0'; brRange.max = '16'; brRange.value = '8'; brRange.step = '1';
    proInputs.borderRadius = brRange;
    var brVal = document.createElement('span'); brVal.className = 'tc-hex'; brVal.textContent = '8px';
    brRange.addEventListener('input', function() { brVal.textContent = brRange.value + 'px'; previewProSettings(); });
    brField.appendChild(brRange);
    brField.appendChild(brVal);
    typoGrid.appendChild(brField);

    typoSection.appendChild(typoGrid);
    proSections.appendChild(typoSection);

    // --- Component Overrides Section ---
    var compSection = document.createElement('details');
    compSection.className = 'tc-pro-section';
    var compSummary = document.createElement('summary');
    var compSummaryText = document.createTextNode('Component Overrides');
    compSummary.appendChild(compSummaryText);
    if (!isPro) {
        var compSummarySpace = document.createTextNode(' ');
        compSummary.appendChild(compSummarySpace);
        var compProBadge = document.createElement('span');
        compProBadge.className = 'pro-badge';
        compProBadge.textContent = 'PRO';
        compSummary.appendChild(compProBadge);
    }
    compSection.appendChild(compSummary);
    var compGrid = document.createElement('div');
    compGrid.className = 'tc-grid';

    // Sidebar bg
    var sbField = document.createElement('div'); sbField.className = 'tc-field';
    var sbLbl = document.createElement('label'); sbLbl.textContent = 'Sidebar Background';
    sbField.appendChild(sbLbl);
    var sbInp = document.createElement('input'); sbInp.type = 'color'; sbInp.value = '#1e293b';
    proInputs.sidebarBg = sbInp;
    sbInp.addEventListener('input', previewProSettings);
    sbField.appendChild(sbInp);
    compGrid.appendChild(sbField);

    // Header bg
    var hbField = document.createElement('div'); hbField.className = 'tc-field';
    var hbLbl = document.createElement('label'); hbLbl.textContent = 'Header Background';
    hbField.appendChild(hbLbl);
    var hbInp = document.createElement('input'); hbInp.type = 'color'; hbInp.value = '#1e293b';
    proInputs.headerBg = hbInp;
    hbInp.addEventListener('input', previewProSettings);
    hbField.appendChild(hbInp);
    compGrid.appendChild(hbField);

    // Card bg
    var cbField = document.createElement('div'); cbField.className = 'tc-field';
    var cbLbl = document.createElement('label'); cbLbl.textContent = 'Card Background';
    cbField.appendChild(cbLbl);
    var cbInp = document.createElement('input'); cbInp.type = 'color'; cbInp.value = '#1e293b';
    proInputs.cardBg = cbInp;
    cbInp.addEventListener('input', previewProSettings);
    cbField.appendChild(cbInp);
    compGrid.appendChild(cbField);

    // Button radius
    var btnrField = document.createElement('div'); btnrField.className = 'tc-field';
    var btnrLbl = document.createElement('label'); btnrLbl.textContent = 'Button Radius';
    btnrField.appendChild(btnrLbl);
    var btnrRange = document.createElement('input'); btnrRange.type = 'range'; btnrRange.min = '0'; btnrRange.max = '16'; btnrRange.value = '6'; btnrRange.step = '1';
    proInputs.btnRadius = btnrRange;
    var btnrVal = document.createElement('span'); btnrVal.className = 'tc-hex'; btnrVal.textContent = '6px';
    btnrRange.addEventListener('input', function() { btnrVal.textContent = btnrRange.value + 'px'; previewProSettings(); });
    btnrField.appendChild(btnrRange);
    btnrField.appendChild(btnrVal);
    compGrid.appendChild(btnrField);

    // Badge style
    var badgeField = document.createElement('div'); badgeField.className = 'tc-field';
    var badgeLbl = document.createElement('label'); badgeLbl.textContent = 'Badge Style';
    badgeField.appendChild(badgeLbl);
    var badgeSel = document.createElement('select');
    proInputs.badgeStyle = badgeSel;
    [{ val: '4', label: 'Rounded' }, { val: '100', label: 'Pill' }, { val: '0', label: 'Square' }].forEach(function(o) {
        var opt = document.createElement('option'); opt.value = o.val; opt.textContent = o.label;
        badgeSel.appendChild(opt);
    });
    badgeSel.addEventListener('change', previewProSettings);
    badgeField.appendChild(badgeSel);
    compGrid.appendChild(badgeField);

    // Toast position
    var tpField = document.createElement('div'); tpField.className = 'tc-field';
    var tpLbl = document.createElement('label'); tpLbl.textContent = 'Toast Position';
    tpField.appendChild(tpLbl);
    var tpSel = document.createElement('select');
    proInputs.toastPosition = tpSel;
    [{ val: 'bottom-right', label: 'Bottom Right' }, { val: 'top-right', label: 'Top Right' }, { val: 'bottom-center', label: 'Bottom Center' }].forEach(function(o) {
        var opt = document.createElement('option'); opt.value = o.val; opt.textContent = o.label;
        tpSel.appendChild(opt);
    });
    tpSel.addEventListener('change', previewProSettings);
    tpField.appendChild(tpSel);
    compGrid.appendChild(tpField);

    compSection.appendChild(compGrid);
    proSections.appendChild(compSection);

    panel.appendChild(proSections);

    // Upgrade CTA for Lite users
    if (!isPro) {
        var cta = document.createElement('div');
        cta.className = 'tc-upgrade-cta';
        var ctaH = document.createElement('strong'); ctaH.textContent = 'Unlock Pro Customizer';
        cta.appendChild(ctaH);
        var ctaP = document.createElement('p');
        ctaP.textContent = 'Typography, component overrides, and full color control. Upgrade your plan to save Pro settings.';
        cta.appendChild(ctaP);
        var ctaBtn = document.createElement('a');
        ctaBtn.href = '/pricing';
        ctaBtn.target = '_blank';
        ctaBtn.className = 'btn btn-primary btn-sm';
        ctaBtn.textContent = 'Upgrade Now';
        cta.appendChild(ctaBtn);
        panel.appendChild(cta);
    }

    // Load colors from a theme
    function loadFromTheme(themeId) {
        var source = null;
        for (var i = 0; i < allThemes.length; i++) {
            if (allThemes[i].id === themeId) { source = allThemes[i]; break; }
        }
        if (!source) return;
        lightCb.checked = !!source.light;
        var css = source.css || '';
        allFields.forEach(function(f) {
            if (!colorInputs[f.key]) return;
            var regex = new RegExp(f.cssVar.replace(/[-]/g, '[-]') + '\\s*:\\s*(#[0-9a-fA-F]{3,8})');
            var match = css.match(regex);
            if (match) {
                colorInputs[f.key].value = match[1];
                if (hexLabels[f.key]) hexLabels[f.key].textContent = match[1];
            }
        });
        // Load Pro settings if present
        if (source._pro) {
            if (source._pro.fontFamily && proInputs.fontFamily) proInputs.fontFamily.value = source._pro.fontFamily;
            if (source._pro.headingScale && proInputs.headingScale) proInputs.headingScale.value = source._pro.headingScale;
            if (source._pro.bodyFontSize && proInputs.bodyFontSize) proInputs.bodyFontSize.value = source._pro.bodyFontSize;
            if (source._pro.borderRadius != null && proInputs.borderRadius) proInputs.borderRadius.value = source._pro.borderRadius;
            if (source._pro.sidebarBg && proInputs.sidebarBg) proInputs.sidebarBg.value = source._pro.sidebarBg;
            if (source._pro.headerBg && proInputs.headerBg) proInputs.headerBg.value = source._pro.headerBg;
            if (source._pro.cardBg && proInputs.cardBg) proInputs.cardBg.value = source._pro.cardBg;
            if (source._pro.btnRadius != null && proInputs.btnRadius) proInputs.btnRadius.value = source._pro.btnRadius;
            if (source._pro.badgeStyle != null && proInputs.badgeStyle) proInputs.badgeStyle.value = source._pro.badgeStyle;
            if (source._pro.toastPosition && proInputs.toastPosition) proInputs.toastPosition.value = source._pro.toastPosition;
        }
    }

    function previewColors() {
        if (isPro) {
            // Pro: use all 11 directly
            var vars = {};
            allFields.forEach(function(f) { if (colorInputs[f.key]) vars[f.key] = colorInputs[f.key].value; });
            liqApplyCustomCss(vars, lightCb.checked);
        } else {
            // Lite: auto-derive from 5 pickers
            var bg = colorInputs.bg.value;
            var text = colorInputs.text.value;
            var accent = colorInputs.accent.value;
            var success = colorInputs.success.value;
            var danger = colorInputs.danger.value;
            var derived = _liqDeriveFullPalette(bg, text, accent, success, danger, lightCb.checked);
            liqApplyCustomCss(derived, lightCb.checked);
            // Update the Pro extra pickers to show derived values (visual only)
            allFields.forEach(function(f) {
                if (liteKeys.indexOf(f.key) < 0 && colorInputs[f.key]) {
                    colorInputs[f.key].value = derived[f.key];
                    if (hexLabels[f.key]) hexLabels[f.key].textContent = derived[f.key];
                }
            });
        }
    }

    function previewProSettings() {
        var root = document.documentElement.style;
        if (proInputs.fontFamily) root.setProperty('--font-family', proInputs.fontFamily.value);
        if (proInputs.headingScale) root.setProperty('--heading-scale', proInputs.headingScale.value);
        if (proInputs.bodyFontSize) root.setProperty('--body-font-size', proInputs.bodyFontSize.value + 'px');
        if (proInputs.borderRadius) root.setProperty('--radius', proInputs.borderRadius.value + 'px');
        if (proInputs.sidebarBg) root.setProperty('--sidebar-bg', proInputs.sidebarBg.value);
        if (proInputs.headerBg) root.setProperty('--header-bg', proInputs.headerBg.value);
        if (proInputs.cardBg) root.setProperty('--card-bg', proInputs.cardBg.value);
        if (proInputs.btnRadius) root.setProperty('--btn-radius', proInputs.btnRadius.value + 'px');
        if (proInputs.badgeStyle) root.setProperty('--badge-radius', proInputs.badgeStyle.value + 'px');
    }

    // Load initial theme
    loadFromTheme(curId);

    startSel.addEventListener('change', function() {
        loadFromTheme(startSel.value);
        previewColors();
        previewProSettings();
    });

    lightCb.addEventListener('change', previewColors);

    // Actions
    var actions = document.createElement('div');
    actions.className = 'tc-actions';

    var saveBtn = document.createElement('button');
    saveBtn.className = 'btn btn-primary btn-sm';
    saveBtn.textContent = 'Save Theme';
    saveBtn.onclick = function() {
        var name = nameInput.value.trim() || 'Custom Theme';
        var vars;
        if (isPro) {
            vars = {};
            allFields.forEach(function(f) { if (colorInputs[f.key]) vars[f.key] = colorInputs[f.key].value; });
            // Include Pro settings as _pro sub-object
            vars._pro = {
                fontFamily: proInputs.fontFamily ? proInputs.fontFamily.value : null,
                headingScale: proInputs.headingScale ? proInputs.headingScale.value : null,
                bodyFontSize: proInputs.bodyFontSize ? proInputs.bodyFontSize.value : null,
                borderRadius: proInputs.borderRadius ? proInputs.borderRadius.value : null,
                sidebarBg: proInputs.sidebarBg ? proInputs.sidebarBg.value : null,
                headerBg: proInputs.headerBg ? proInputs.headerBg.value : null,
                cardBg: proInputs.cardBg ? proInputs.cardBg.value : null,
                btnRadius: proInputs.btnRadius ? proInputs.btnRadius.value : null,
                badgeStyle: proInputs.badgeStyle ? proInputs.badgeStyle.value : null,
                toastPosition: proInputs.toastPosition ? proInputs.toastPosition.value : null,
            };
        } else {
            // Lite: save the 5 + derived
            var bg = colorInputs.bg.value;
            var text = colorInputs.text.value;
            var accent = colorInputs.accent.value;
            var success = colorInputs.success.value;
            var danger = colorInputs.danger.value;
            vars = _liqDeriveFullPalette(bg, text, accent, success, danger, lightCb.checked);
        }
        var theme = liqSaveCustomTheme(name, vars, lightCb.checked);
        liqApplyTheme(theme.id, themes);
        toast('Theme "' + name + '" saved!');
        panel.remove();
        liqLoadThemes().then(function(t) { renderThemePicker(parent, t); });
    };
    actions.appendChild(saveBtn);

    var cancelBtn = document.createElement('button');
    cancelBtn.className = 'btn btn-ghost btn-sm';
    cancelBtn.textContent = 'Cancel';
    cancelBtn.onclick = function() {
        liqApplyTheme(curId, allThemes);
        panel.remove();
    };
    actions.appendChild(cancelBtn);

    panel.appendChild(actions);

    // Insert after theme picker
    var picker = parent.querySelector('.theme-picker-wrap');
    if (picker && picker.nextSibling) {
        parent.insertBefore(panel, picker.nextSibling);
    } else if (picker) {
        parent.appendChild(panel);
    } else {
        var h2El = parent.querySelector('h2');
        if (h2El && h2El.nextSibling) parent.insertBefore(panel, h2El.nextSibling);
        else parent.appendChild(panel);
    }
}

/* ── Theme Export/Import ─────────────────────────────────────────────── */
function liqExportTheme(themes, themeId) {
    var theme = null;
    var allT = themes.concat(_liqCustomThemes);
    for (var i = 0; i < allT.length; i++) {
        if (allT[i].id === themeId) { theme = allT[i]; break; }
    }
    if (!theme) { toast('Theme not found'); return; }

    // Parse CSS vars into object
    var cssVars = {};
    if (theme.css_vars) {
        cssVars = theme.css_vars;
    } else if (theme.css) {
        var varMap = { '--bg':'bg', '--surface':'surface', '--surface2':'surface2', '--border':'border',
            '--text':'text', '--text-muted':'text_muted', '--accent':'accent', '--accent-hover':'accent_hover',
            '--success':'success', '--danger':'danger', '--warning':'warning' };
        for (var k in varMap) {
            var regex = new RegExp(k.replace(/[-]/g, '[-]') + '\\s*:\\s*(#[0-9a-fA-F]{3,8})');
            var match = theme.css.match(regex);
            if (match) cssVars[varMap[k]] = match[1];
        }
    }

    // Remove _pro from css_vars (it goes in its own section)
    var proSettings = null;
    if (cssVars._pro) {
        proSettings = cssVars._pro;
        cssVars = Object.assign({}, cssVars);
        delete cssVars._pro;
    }

    var data = {
        luperiq_theme: true,
        version: 2,
        name: theme.name,
        description: theme.description || '',
        light: !!theme.light,
        tier: proSettings ? 'pro' : 'lite',
        css_vars: cssVars
    };
    if (proSettings) {
        data.pro = proSettings;
    }
    lqExportJSON(data, 'luperiq-theme-' + themeId + '.json');
    toast('Theme exported!');
}

function liqImportTheme(builtInThemes) {
    lqImportJSON(function(data) {
        if (!data.luperiq_theme) { toast('Not a valid LuperIQ theme file'); return; }

        var cssVars, name, isLight;

        if (data.version >= 2) {
            // v2 format: colors in css_vars, optional pro section
            if (!data.css_vars) { toast('Theme file missing color data'); return; }
            cssVars = data.css_vars;
            name = data.name || 'Imported Theme';
            isLight = !!data.light;
            // Attach Pro settings if present
            if (data.pro) {
                cssVars = Object.assign({}, cssVars);
                cssVars._pro = data.pro;
            }
        } else {
            // v1 format: colors in css_vars directly
            if (!data.css_vars) { toast('Theme file missing color data'); return; }
            cssVars = data.css_vars;
            name = data.name || 'Imported Theme';
            isLight = !!data.light;
        }

        // Validate required keys
        var required = ['bg', 'surface', 'text', 'accent'];
        for (var i = 0; i < required.length; i++) {
            if (!cssVars[required[i]]) { toast('Missing required color: ' + required[i]); return; }
        }

        var theme = liqSaveCustomTheme(name, cssVars, isLight);
        liqApplyTheme(theme.id, builtInThemes);
        toast('Theme "' + name + '" imported!');
        var main = document.getElementById('adminMain');
        if (main) {
            liqLoadThemes().then(function(t) { renderThemePicker(main, t); });
        }
    });
}

/* ── AI Theme Panel ──────────────────────────────────────────────────── */
function renderAiThemePanel(parent, themes) {
    // Remove existing panels
    var existing = parent.querySelector('.ai-theme-panel');
    if (existing) { existing.remove(); return; } // toggle off
    var custPanel = parent.querySelector('.theme-customizer');
    if (custPanel) custPanel.remove();

    var panel = document.createElement('div');
    panel.className = 'ai-theme-panel';

    var h3 = document.createElement('h3');
    h3.textContent = 'AI Theme Generator';
    panel.appendChild(h3);

    var hint = document.createElement('div');
    hint.className = 'ai-hint';
    hint.textContent = 'Describe the vibe, mood, or aesthetic you want. The AI generates a matching 11-color palette.';
    panel.appendChild(hint);

    var textarea = document.createElement('textarea');
    textarea.placeholder = 'Examples:\n\u2022 "I run a pest control company in Texas \u2014 rugged, outdoor, earthy browns and greens"\n\u2022 "Modern dental office \u2014 clean, calming, light blues and whites, professional"\n\u2022 "BBQ restaurant with a smoky, rustic feel \u2014 charcoal, burnt orange, warm wood tones"\n\u2022 "Kids\' birthday party planner \u2014 fun, bright, playful purples and pinks"\n\u2022 "Law firm \u2014 dark navy, gold accents, serious and trustworthy"\n\u2022 "Surf shop on the coast \u2014 ocean blues, sandy beige, relaxed tropical vibe"';
    panel.appendChild(textarea);

    // Name + light/dark row
    var optRow = document.createElement('div');
    optRow.style.cssText = 'display:flex;gap:12px;align-items:center;margin-bottom:12px;';
    var nameInput = document.createElement('input');
    nameInput.type = 'text';
    nameInput.placeholder = 'Theme name (optional)';
    nameInput.style.cssText = 'flex:1;padding:6px 10px;background:var(--bg);border:1px solid var(--border);border-radius:6px;color:var(--text);font-size:13px;max-width:220px;';
    optRow.appendChild(nameInput);
    var lightLbl = document.createElement('label');
    lightLbl.style.cssText = 'display:flex;align-items:center;gap:6px;font-size:13px;color:var(--text-muted);cursor:pointer;';
    var lightCb = document.createElement('input');
    lightCb.type = 'checkbox';
    lightLbl.appendChild(lightCb);
    lightLbl.appendChild(document.createTextNode('Light theme'));
    optRow.appendChild(lightLbl);
    panel.appendChild(optRow);

    var actionsDiv = document.createElement('div');
    actionsDiv.className = 'ai-actions';

    var snapshotBtn = document.createElement('button');
    snapshotBtn.className = 'btn btn-ghost btn-sm';
    snapshotBtn.textContent = 'Save Snapshot';

    var undoBtn = document.createElement('button');
    undoBtn.className = 'btn btn-ghost btn-sm';
    undoBtn.textContent = 'Undo AI Preview';
    undoBtn.disabled = true;

    var genBtn = document.createElement('button');
    genBtn.className = 'btn btn-primary btn-sm';
    genBtn.textContent = 'Generate Theme';

    var cancelBtn = document.createElement('button');
    cancelBtn.className = 'btn btn-ghost btn-sm';
    cancelBtn.textContent = 'Cancel';
    cancelBtn.onclick = function() { panel.remove(); };

    actionsDiv.appendChild(snapshotBtn);
    actionsDiv.appendChild(undoBtn);
    actionsDiv.appendChild(genBtn);
    actionsDiv.appendChild(cancelBtn);
    panel.appendChild(actionsDiv);

    // Feedback container — LiqAI renders feedback bar here
    var feedbackContainer = document.createElement('div');
    panel.appendChild(feedbackContainer);

    // Closure state for generated theme
    var lastGeneratedColors = null;
    var lastThemeName = '';
    var curId = localStorage.getItem('liq-theme-id') || 'azle';
    var lastSnapshot = null;

    function captureThemeSnapshot(label) {
        var themeStyle = document.getElementById('liq-theme');
        lastSnapshot = {
            label: label || 'manual',
            takenAt: new Date().toISOString(),
            themeId: localStorage.getItem('liq-theme-id') || curId,
            css: localStorage.getItem('liq-theme-css') || (themeStyle ? themeStyle.textContent : ''),
            light: document.body.classList.contains('liq-light'),
            name: nameInput.value.trim() || lastThemeName || 'AI Theme'
        };
        undoBtn.disabled = !lastSnapshot;
        return lastSnapshot;
    }

    function restoreThemeSnapshot(snapshot) {
        if (!snapshot) return;
        var themeStyle = document.getElementById('liq-theme');
        if (!themeStyle) {
            themeStyle = document.createElement('style');
            themeStyle.id = 'liq-theme';
            document.head.appendChild(themeStyle);
        }
        themeStyle.textContent = snapshot.css || '';
        localStorage.setItem('liq-theme-css', snapshot.css || '');
        if (snapshot.themeId) localStorage.setItem('liq-theme-id', snapshot.themeId);
        if (snapshot.light) document.body.classList.add('liq-light');
        else document.body.classList.remove('liq-light');
        if (typeof toast === 'function') toast('Restored pre-AI theme snapshot');
    }

    snapshotBtn.onclick = function() {
        var snapshot = captureThemeSnapshot('manual');
        if (!snapshot) return;
        lqExportJSON(snapshot, 'theme-ai-snapshot-' + snapshot.takenAt.replace(/[:.]/g, '-') + '.json');
        if (typeof toast === 'function') toast('Theme snapshot downloaded');
    };

    undoBtn.onclick = function() {
        restoreThemeSnapshot(lastSnapshot);
    };

    genBtn.onclick = function() {
        var desc = textarea.value.trim();
        if (!desc) { toast('Please describe the vibe you want'); return; }
        lastThemeName = nameInput.value.trim() || 'AI Theme';
        captureThemeSnapshot('pre-ai');

        LiqAI.generate({
            feature: 'theme',
            userInput: desc,
            container: feedbackContainer,
            context: { light: lightCb.checked, name: lastThemeName },
            onResult: function(result) {
                lastGeneratedColors = result;
                // Apply colors live as preview
                liqApplyCustomCss(result, lightCb.checked);
            },
            onKeep: function() {
                if (lastGeneratedColors) {
                    var theme = liqSaveCustomTheme(lastThemeName, lastGeneratedColors, lightCb.checked);
                    liqApplyTheme(theme.id, themes.concat(_liqCustomThemes));
                    toast('Theme "' + lastThemeName + '" saved!');
                }
                panel.remove();
                liqLoadThemes().then(function(t) { renderThemePicker(parent, t); });
            },
            onRetry: function() {
                // Revert to previous theme before retry
                restoreThemeSnapshot(lastSnapshot);
            },
            onError: function(msg) {
                // Revert preview on error
                restoreThemeSnapshot(lastSnapshot);
            }
        });
    };

    // Insert after theme picker
    var picker = parent.querySelector('.theme-picker-wrap');
    if (picker && picker.nextSibling) {
        parent.insertBefore(panel, picker.nextSibling);
    } else {
        parent.appendChild(panel);
    }
}

// Collapsible sidebar sections — accordion style (only one open at a time)
(function() {
    const stored = JSON.parse(localStorage.getItem('lq_sidebar_open') || '{"content":true}');
    // Find which section should be open (last stored, or content by default)
    let activeSection = 'content';
    for (const key in stored) { if (stored[key]) activeSection = key; }
    document.querySelectorAll('.section-links').forEach(el => {
        const key = el.dataset.section;
        if (key === activeSection) el.classList.add('open');
        else el.classList.remove('open');
    });
    document.querySelectorAll('.section-toggle').forEach(el => {
        const key = el.dataset.section;
        const links = document.querySelector('.section-links[data-section="' + key + '"]');
        if (links && links.classList.contains('open')) el.classList.add('open');
        el.addEventListener('click', () => {
            if (!links) return;
            const wasOpen = links.classList.contains('open');
            // Close ALL sections first (accordion)
            document.querySelectorAll('.section-links').forEach(s => s.classList.remove('open'));
            document.querySelectorAll('.section-toggle').forEach(t => t.classList.remove('open'));
            // Open this one if it was closed
            if (!wasOpen) {
                links.classList.add('open');
                el.classList.add('open');
            }
            // Save state
            const state = {};
            document.querySelectorAll('.section-links').forEach(s => {
                state[s.dataset.section] = s.classList.contains('open');
            });
            localStorage.setItem('lq_sidebar_open', JSON.stringify(state));
        });
    });
})();
"####;
