//! Industry sub-specialty taxonomy — data-only layer on top of SiteTypeDefinition.
//!
//! Categories group industries for funnel/catalog display.
//! Sub-specialties define niche variants within an industry that inherit modules,
//! theme, and nav from their parent but override display text, CTA, and pages.

use serde::{Deserialize, Serialize};

// ─── Data Structures ────────────────────────────────────────────────────────

/// Top-level grouping for the site catalog funnel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustryCategory {
    pub slug: String,
    pub name: String,
    pub emoji: String,
    pub description: String,
    pub display_order: u32,
}

/// A niche within a parent industry. Inherits modules/theme from the parent
/// SiteTypeDefinition but can override display, CTA, nav, pages, and SEO.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustrySubSpecialty {
    pub slug: String,
    /// Links to an existing SiteTypeDefinition slug (e.g. "restaurant", "hvac")
    pub parent_industry: String,
    /// Links to an IndustryCategory slug (e.g. "restaurants", "home-services")
    pub category: String,
    pub name: String,
    pub emoji: String,
    pub description: String,
    pub tagline: String,
    /// Used for SEO title templates: "{business_name} -- {seo_title_suffix} in {city}"
    pub seo_title_suffix: String,
    pub default_cta_text: String,
    pub default_cta_url: String,
    /// Additional nav items beyond what the parent industry provides
    pub unique_nav_items: Vec<String>,
    /// Additional pages to create beyond the parent's defaults
    pub unique_pages: Vec<String>,
    pub display_order: u32,
}

// ─── Category Data ──────────────────────────────────────────────────────────

/// Returns all industry categories for the catalog funnel.
pub fn all_categories() -> Vec<IndustryCategory> {
    vec![
        // ── Community ──
        cat(
            "family",
            "Family",
            "\u{1F3E0}",
            "Families, roommates, households, care circles",
            1,
        ),
        cat(
            "faith",
            "Church & Faith",
            "\u{2764}\u{FE0F}",
            "Churches, small groups, mission teams",
            2,
        ),
        cat(
            "education",
            "Schools & Learning",
            "\u{1F4DA}",
            "Classrooms, homeschool, co-ops",
            3,
        ),
        cat(
            "sports",
            "Sports & Teams",
            "\u{26BD}",
            "Sports teams, scouts, fitness groups",
            4,
        ),
        cat(
            "clubs",
            "Clubs & Hobbies",
            "\u{1F3AF}",
            "Book clubs, creative crews, social groups",
            5,
        ),
        cat(
            "work",
            "Work Teams",
            "\u{1F4BC}",
            "Internal teams, nonprofits, maker spaces",
            6,
        ),
        cat(
            "events",
            "Weddings & Events",
            "\u{1F48D}",
            "Weddings, reunions, memorials, travel",
            7,
        ),
        // ── Business ──
        cat(
            "restaurants",
            "Restaurants & Food",
            "\u{1F37D}\u{FE0F}",
            "Restaurants, bakeries, coffee shops, food trucks",
            10,
        ),
        cat(
            "beauty",
            "Beauty & Wellness",
            "\u{1F487}",
            "Salons, barbers, spas, estheticians",
            11,
        ),
        cat(
            "medical",
            "Medical & Health",
            "\u{1FA7A}",
            "Doctors, dentists, chiropractors, vets, therapists",
            12,
        ),
        cat(
            "home-services",
            "Home Services",
            "\u{1F3E0}",
            "Roofing, painting, cleaning, handyman, moving",
            13,
        ),
        cat(
            "hvac-plumbing",
            "HVAC, Plumbing & Electrical",
            "\u{2744}\u{FE0F}",
            "HVAC, plumbing, electrical, refrigeration",
            14,
        ),
        cat(
            "pest-lawn",
            "Pest Control & Lawn",
            "\u{1F41B}",
            "Pest control, landscaping, tree service, irrigation",
            15,
        ),
        cat(
            "auto",
            "Auto Services",
            "\u{1F697}",
            "Auto repair, oil change, body shop, detailing, tires",
            16,
        ),
        cat(
            "repair",
            "Repair & Tech",
            "\u{1F4F1}",
            "Phone repair, computer repair, electronics, smart home",
            17,
        ),
        cat(
            "professional",
            "Professional Services",
            "\u{1F4BC}",
            "Attorneys, accountants, insurance, real estate",
            18,
        ),
        cat(
            "creative",
            "Creative & Commerce",
            "\u{1F3A8}",
            "Artisan markets, photographers, print shops, studios",
            19,
        ),
        cat(
            "pets",
            "Pet Services",
            "\u{1F43E}",
            "Pet grooming, dog training, boarding, vet clinics",
            20,
        ),
        cat(
            "childcare",
            "Childcare & Education",
            "\u{1F476}",
            "Daycare, tutoring centers, after-school programs",
            21,
        ),
    ]
}

// ─── Sub-Specialty Data ─────────────────────────────────────────────────────

/// Returns all industry sub-specialties. Each inherits from its parent industry.
pub fn all_subspecialties() -> Vec<IndustrySubSpecialty> {
    vec![
        // ── Restaurants & Food ──────────────────────────────────────────
        sub(
            "fine-dining",
            "restaurant",
            "restaurants",
            "Fine Dining",
            "\u{1F37E}",
            "Upscale dining with reservations and wine lists",
            "Exquisite cuisine, impeccable service",
            "Reserve Your Table",
            "/reservations",
            1,
        ),
        sub(
            "fast-casual",
            "restaurant",
            "restaurants",
            "Fast Casual",
            "\u{1F354}",
            "Counter-service with quality ingredients",
            "Fresh food, fast service",
            "Order Now",
            "/menu",
            2,
        ),
        sub(
            "food-truck",
            "restaurant",
            "restaurants",
            "Food Truck",
            "\u{1F69A}",
            "Mobile food service with location tracking",
            "Find us around town",
            "See Today's Location",
            "/locations",
            3,
        ),
        sub(
            "pizza-shop",
            "restaurant",
            "restaurants",
            "Pizza Shop",
            "\u{1F355}",
            "Pizza delivery and dine-in",
            "Hot pies, fast delivery",
            "Order Pizza",
            "/menu",
            4,
        ),
        sub(
            "bbq",
            "restaurant",
            "restaurants",
            "BBQ & Smokehouse",
            "\u{1F356}",
            "Smoked meats and Southern sides",
            "Low and slow, worth the wait",
            "See Our Menu",
            "/menu",
            5,
        ),
        sub(
            "bar-grill",
            "restaurant",
            "restaurants",
            "Bar & Grill",
            "\u{1F37A}",
            "Casual dining with full bar",
            "Good food, cold drinks",
            "See Our Menu",
            "/menu",
            6,
        ),
        sub(
            "catering-company",
            "restaurant",
            "restaurants",
            "Catering Company",
            "\u{1F370}",
            "Event catering and meal prep",
            "We bring the feast to you",
            "Request a Quote",
            "/catering",
            7,
        ),
        sub(
            "deli-sandwich",
            "restaurant",
            "restaurants",
            "Deli & Sandwich Shop",
            "\u{1F96A}",
            "Fresh sandwiches and deli meats",
            "Made fresh, made right",
            "Order Ahead",
            "/menu",
            8,
        ),
        sub(
            "juice-bar",
            "restaurant",
            "restaurants",
            "Juice Bar & Smoothie",
            "\u{1F34A}",
            "Fresh juices, smoothies, and bowls",
            "Fuel your body",
            "See Our Menu",
            "/menu",
            9,
        ),
        sub(
            "ice-cream",
            "restaurant",
            "restaurants",
            "Ice Cream & Desserts",
            "\u{1F366}",
            "Ice cream shop and dessert parlor",
            "Life is sweet",
            "See Our Flavors",
            "/menu",
            10,
        ),
        // ── Beauty & Wellness ───────────────────────────────────────────
        sub(
            "hair-salon",
            "salon",
            "beauty",
            "Hair Salon",
            "\u{1F487}",
            "Cuts, color, and styling",
            "Your best look starts here",
            "Book Appointment",
            "/salon/book",
            1,
        ),
        sub(
            "barber-shop",
            "salon",
            "beauty",
            "Barber Shop",
            "\u{1F488}",
            "Classic cuts and grooming",
            "Sharp cuts, clean fades",
            "Book Your Cut",
            "/salon/book",
            2,
        ),
        sub(
            "nail-salon",
            "salon",
            "beauty",
            "Nail Salon",
            "\u{1F485}",
            "Manicures, pedicures, and nail art",
            "Treat yourself",
            "Book Appointment",
            "/salon/book",
            3,
        ),
        sub(
            "spa-massage",
            "salon",
            "beauty",
            "Spa & Massage",
            "\u{1F9D6}",
            "Relaxation and therapeutic massage",
            "Restore your calm",
            "Book a Session",
            "/salon/book",
            4,
        ),
        sub(
            "esthetician",
            "salon",
            "beauty",
            "Esthetician & Skincare",
            "\u{2728}",
            "Facials, peels, and skincare treatments",
            "Glow from within",
            "Book a Facial",
            "/salon/book",
            5,
        ),
        sub(
            "tattoo",
            "salon",
            "beauty",
            "Tattoo & Piercing",
            "\u{1F3A8}",
            "Custom tattoo art and piercings",
            "Wear your story",
            "Book a Consultation",
            "/contact",
            6,
        ),
        sub(
            "lash-brow",
            "salon",
            "beauty",
            "Lash & Brow Studio",
            "\u{1F441}\u{FE0F}",
            "Lash extensions and brow shaping",
            "Frame your face",
            "Book Appointment",
            "/salon/book",
            7,
        ),
        // ── Medical & Health ────────────────────────────────────────────
        sub(
            "family-medicine",
            "medical",
            "medical",
            "Family Medicine",
            "\u{1FA7A}",
            "Primary care for the whole family",
            "Your family's health, our priority",
            "Request Appointment",
            "/book",
            1,
        ),
        sub(
            "dentist",
            "medical",
            "medical",
            "Dentist",
            "\u{1F9B7}",
            "General and cosmetic dentistry",
            "Healthy smiles for life",
            "Schedule Your Visit",
            "/book",
            2,
        ),
        sub(
            "chiropractor",
            "medical",
            "medical",
            "Chiropractor",
            "\u{1F9D8}",
            "Spinal adjustments and wellness",
            "Align your health",
            "Book Adjustment",
            "/book",
            3,
        ),
        sub(
            "physical-therapy",
            "medical",
            "medical",
            "Physical Therapy",
            "\u{1F4AA}",
            "Rehabilitation and recovery",
            "Move better, feel better",
            "Start Your Recovery",
            "/book",
            4,
        ),
        sub(
            "optometrist",
            "medical",
            "medical",
            "Optometrist",
            "\u{1F453}",
            "Eye exams and vision care",
            "See life clearly",
            "Schedule Eye Exam",
            "/book",
            5,
        ),
        sub(
            "veterinarian",
            "medical",
            "medical",
            "Veterinarian",
            "\u{1F43E}",
            "Pet healthcare and surgery",
            "Compassionate pet care",
            "Book a Visit",
            "/book",
            6,
        ),
        sub(
            "counseling",
            "medical",
            "medical",
            "Counseling & Therapy",
            "\u{1F49A}",
            "Mental health and wellness",
            "A safe space to grow",
            "Schedule a Session",
            "/book",
            7,
        ),
        sub(
            "dermatology",
            "medical",
            "medical",
            "Dermatology",
            "\u{2728}",
            "Skin care and treatment",
            "Healthy skin, confident you",
            "Book Consultation",
            "/book",
            8,
        ),
        sub(
            "urgent-care",
            "medical",
            "medical",
            "Urgent Care",
            "\u{1F3E5}",
            "Walk-in medical care",
            "Care when you need it",
            "Check Wait Times",
            "/",
            9,
        ),
        // ── HVAC, Plumbing & Electrical ─────────────────────────────────
        sub(
            "hvac-general",
            "hvac",
            "hvac-plumbing",
            "HVAC Service",
            "\u{2744}\u{FE0F}",
            "Heating, cooling, and air quality",
            "Comfort in every season",
            "Schedule Service",
            "/book",
            1,
        ),
        sub(
            "ac-repair",
            "hvac",
            "hvac-plumbing",
            "AC Installation & Repair",
            "\u{1F4A8}",
            "Air conditioning specialists",
            "Stay cool when it counts",
            "Schedule AC Service",
            "/book",
            2,
        ),
        sub(
            "commercial-refrigeration",
            "hvac",
            "hvac-plumbing",
            "Commercial Refrigeration",
            "\u{1F9CA}",
            "Walk-in coolers, freezers, display cases",
            "Keep it cold, keep it fresh",
            "Request Service",
            "/contact",
            3,
        ),
        sub(
            "heating",
            "hvac",
            "hvac-plumbing",
            "Heating Service",
            "\u{1F525}",
            "Furnace, boiler, and heat pump service",
            "Warmth you can count on",
            "Schedule Service",
            "/book",
            4,
        ),
        sub(
            "duct-cleaning",
            "hvac",
            "hvac-plumbing",
            "Duct Cleaning",
            "\u{1F32C}\u{FE0F}",
            "Air duct cleaning and sanitizing",
            "Breathe cleaner air",
            "Get a Quote",
            "/contact",
            5,
        ),
        sub(
            "plumbing-general",
            "plumbing",
            "hvac-plumbing",
            "Plumbing Service",
            "\u{1F4A7}",
            "Full-service plumbing repairs and installation",
            "We fix it right the first time",
            "Schedule Service",
            "/book",
            6,
        ),
        sub(
            "drain-cleaning",
            "plumbing",
            "hvac-plumbing",
            "Drain Cleaning",
            "\u{1F6BF}",
            "Clogged drains and sewer lines",
            "Flow restored, guaranteed",
            "Book Drain Service",
            "/book",
            7,
        ),
        sub(
            "water-heater",
            "plumbing",
            "hvac-plumbing",
            "Water Heater Service",
            "\u{1F6BF}",
            "Tank and tankless water heater install and repair",
            "Hot water, on demand",
            "Schedule Service",
            "/book",
            8,
        ),
        sub(
            "electrical-general",
            "electrical",
            "hvac-plumbing",
            "Electrical Service",
            "\u{26A1}",
            "Residential and commercial electrical",
            "Safe, reliable, up to code",
            "Schedule Service",
            "/book",
            9,
        ),
        sub(
            "solar",
            "electrical",
            "hvac-plumbing",
            "Solar Installation",
            "\u{2600}\u{FE0F}",
            "Solar panel installation and maintenance",
            "Power your home with the sun",
            "Get a Solar Quote",
            "/contact",
            10,
        ),
        sub(
            "ev-charger",
            "electrical",
            "hvac-plumbing",
            "EV Charger Installation",
            "\u{1F50C}",
            "Home and commercial EV charging stations",
            "Charge at home, drive everywhere",
            "Get a Quote",
            "/contact",
            11,
        ),
        sub(
            "generator",
            "electrical",
            "hvac-plumbing",
            "Generator Service",
            "\u{26A1}",
            "Standby generator install and maintenance",
            "Power when the grid goes down",
            "Schedule Service",
            "/book",
            12,
        ),
        // ── Pest Control & Lawn ─────────────────────────────────────────
        sub(
            "pest-general",
            "pest-control",
            "pest-lawn",
            "Pest Control",
            "\u{1F41B}",
            "General pest management and prevention",
            "Pests out, peace of mind in",
            "Get a Free Inspection",
            "/book",
            1,
        ),
        sub(
            "termite",
            "pest-control",
            "pest-lawn",
            "Termite Treatment",
            "\u{1F41C}",
            "Termite inspection, treatment, and prevention",
            "Protect your biggest investment",
            "Schedule Inspection",
            "/book",
            2,
        ),
        sub(
            "wildlife-removal",
            "pest-control",
            "pest-lawn",
            "Wildlife Removal",
            "\u{1F99D}",
            "Humane animal removal and exclusion",
            "Safe removal, permanent prevention",
            "Call for Service",
            "/contact",
            3,
        ),
        sub(
            "mosquito",
            "pest-control",
            "pest-lawn",
            "Mosquito Control",
            "\u{1F99F}",
            "Yard treatment and misting systems",
            "Take back your backyard",
            "Get a Quote",
            "/contact",
            4,
        ),
        sub(
            "lawn-care",
            "landscaping",
            "pest-lawn",
            "Lawn Care & Mowing",
            "\u{1F33F}",
            "Regular mowing, edging, and fertilization",
            "A lawn you'll love coming home to",
            "Get a Quote",
            "/contact",
            5,
        ),
        sub(
            "tree-service",
            "landscaping",
            "pest-lawn",
            "Tree Service",
            "\u{1F333}",
            "Trimming, removal, and stump grinding",
            "Expert tree care, safely done",
            "Request Estimate",
            "/contact",
            6,
        ),
        sub(
            "irrigation",
            "landscaping",
            "pest-lawn",
            "Irrigation & Sprinklers",
            "\u{1F4A6}",
            "Sprinkler install, repair, and winterization",
            "Every drop where it counts",
            "Schedule Service",
            "/book",
            7,
        ),
        sub(
            "hardscaping",
            "landscaping",
            "pest-lawn",
            "Hardscaping & Pavers",
            "\u{1F9F1}",
            "Patios, walkways, retaining walls",
            "Built to last, designed to impress",
            "Get a Design Consultation",
            "/contact",
            8,
        ),
        // ── Auto Services ───────────────────────────────────────────────
        sub(
            "auto-general",
            "auto-repair",
            "auto",
            "Auto Repair",
            "\u{1F697}",
            "Full-service auto repair and maintenance",
            "Honest repairs, fair prices",
            "Schedule Service",
            "/book",
            1,
        ),
        sub(
            "oil-change",
            "auto-repair",
            "auto",
            "Oil Change & Quick Lube",
            "\u{1F6E2}\u{FE0F}",
            "Fast oil changes and fluid services",
            "In and out in minutes",
            "Drive In Today",
            "/",
            2,
        ),
        sub(
            "tire-shop",
            "auto-repair",
            "auto",
            "Tire Shop",
            "\u{1F6DE}",
            "Tire sales, mounting, balancing, and alignment",
            "The right tires for your ride",
            "Shop Tires",
            "/services",
            3,
        ),
        sub(
            "body-shop",
            "auto-repair",
            "auto",
            "Body Shop & Collision",
            "\u{1F3A8}",
            "Collision repair and paint",
            "Like it never happened",
            "Get an Estimate",
            "/contact",
            4,
        ),
        sub(
            "auto-detailing",
            "auto-repair",
            "auto",
            "Auto Detailing",
            "\u{2728}",
            "Interior and exterior detailing",
            "Show-car clean, every time",
            "Book a Detail",
            "/book",
            5,
        ),
        sub(
            "diesel",
            "auto-repair",
            "auto",
            "Diesel Mechanic",
            "\u{1F69B}",
            "Diesel truck and fleet repair",
            "Heavy-duty expertise",
            "Schedule Service",
            "/book",
            6,
        ),
        // ── Repair & Tech ───────────────────────────────────────────────
        sub(
            "phone-repair",
            "cell-phone-repair",
            "repair",
            "Cell Phone Repair",
            "\u{1F4F1}",
            "Screen replacement, battery, and water damage",
            "Most repairs in under an hour",
            "Get a Quote",
            "/services",
            1,
        ),
        sub(
            "computer-repair",
            "cell-phone-repair",
            "repair",
            "Computer Repair",
            "\u{1F4BB}",
            "Laptop and desktop repair and upgrades",
            "Fast fixes for all brands",
            "Bring It In",
            "/services",
            2,
        ),
        sub(
            "game-console",
            "electronics-repair",
            "repair",
            "Game Console Repair",
            "\u{1F3AE}",
            "PlayStation, Xbox, Nintendo repair",
            "Get back in the game",
            "Get a Quote",
            "/services",
            3,
        ),
        sub(
            "smart-home",
            "electronics-repair",
            "repair",
            "Smart Home Installation",
            "\u{1F3E0}",
            "Smart locks, cameras, thermostats, lighting",
            "Make your home smarter",
            "Schedule Install",
            "/book",
            4,
        ),
        // ── Home Services ───────────────────────────────────────────────
        sub(
            "roofing",
            "general",
            "home-services",
            "Roofing",
            "\u{1F3E0}",
            "Roof repair, replacement, and inspection",
            "The roof over your head, done right",
            "Get a Free Inspection",
            "/contact",
            1,
        ),
        sub(
            "painting",
            "general",
            "home-services",
            "Painting",
            "\u{1F3A8}",
            "Interior and exterior painting",
            "Transform your space",
            "Get a Free Estimate",
            "/contact",
            2,
        ),
        sub(
            "carpet-cleaning",
            "general",
            "home-services",
            "Carpet Cleaning",
            "\u{1F9F9}",
            "Deep carpet and upholstery cleaning",
            "Fresh, clean, renewed",
            "Book a Cleaning",
            "/book",
            3,
        ),
        sub(
            "house-cleaning",
            "general",
            "home-services",
            "House Cleaning",
            "\u{2728}",
            "Residential cleaning and maid service",
            "Come home to clean",
            "Book a Cleaning",
            "/book",
            4,
        ),
        sub(
            "handyman",
            "general",
            "home-services",
            "Handyman",
            "\u{1F527}",
            "Repairs, assembly, and odd jobs",
            "One call fixes it all",
            "Request Service",
            "/contact",
            5,
        ),
        sub(
            "locksmith",
            "general",
            "home-services",
            "Locksmith",
            "\u{1F511}",
            "Lock installation, rekey, and emergency lockout",
            "Locked out? We're on the way",
            "Call Now",
            "/contact",
            6,
        ),
        sub(
            "pressure-washing",
            "general",
            "home-services",
            "Pressure Washing",
            "\u{1F4A6}",
            "House, driveway, and deck washing",
            "Blast away the grime",
            "Get a Quote",
            "/contact",
            7,
        ),
        sub(
            "garage-door",
            "general",
            "home-services",
            "Garage Door",
            "\u{1F6AA}",
            "Garage door repair and installation",
            "Opens when you need it",
            "Schedule Repair",
            "/book",
            8,
        ),
        sub(
            "moving",
            "general",
            "home-services",
            "Moving Company",
            "\u{1F4E6}",
            "Local and long-distance moving",
            "Your move, made easy",
            "Get a Moving Quote",
            "/contact",
            9,
        ),
        sub(
            "flooring",
            "general",
            "home-services",
            "Flooring",
            "\u{1F3E0}",
            "Hardwood, tile, carpet, and LVP installation",
            "The foundation of beautiful rooms",
            "Get a Free Estimate",
            "/contact",
            10,
        ),
        sub(
            "fencing",
            "general",
            "home-services",
            "Fencing",
            "\u{1F3E1}",
            "Wood, vinyl, chain link, and iron fencing",
            "Define your space",
            "Get a Quote",
            "/contact",
            11,
        ),
        // ── Professional Services ───────────────────────────────────────
        sub(
            "attorney",
            "general",
            "professional",
            "Attorney / Law Firm",
            "\u{2696}\u{FE0F}",
            "Legal representation and counsel",
            "Justice, advocacy, results",
            "Schedule Consultation",
            "/contact",
            1,
        ),
        sub(
            "accountant",
            "general",
            "professional",
            "Accountant / CPA",
            "\u{1F4CA}",
            "Tax preparation and bookkeeping",
            "Numbers you can trust",
            "Book a Consultation",
            "/contact",
            2,
        ),
        sub(
            "insurance",
            "general",
            "professional",
            "Insurance Agent",
            "\u{1F6E1}\u{FE0F}",
            "Home, auto, life, and business insurance",
            "Protection for what matters",
            "Get a Quote",
            "/contact",
            3,
        ),
        sub(
            "real-estate",
            "general",
            "professional",
            "Real Estate Agent",
            "\u{1F3E0}",
            "Buying, selling, and property management",
            "Your home journey starts here",
            "Contact Me",
            "/contact",
            4,
        ),
        sub(
            "photographer",
            "general",
            "professional",
            "Photographer",
            "\u{1F4F7}",
            "Portrait, event, and commercial photography",
            "Moments, captured beautifully",
            "View Portfolio",
            "/gallery",
            5,
        ),
        // ── Pet Services ────────────────────────────────────────────────
        sub(
            "pet-grooming",
            "general",
            "pets",
            "Pet Grooming",
            "\u{1F9FC}",
            "Dog and cat grooming and spa",
            "Pampered pets, happy owners",
            "Book a Groom",
            "/book",
            1,
        ),
        sub(
            "dog-training",
            "general",
            "pets",
            "Dog Training",
            "\u{1F9AE}",
            "Obedience, behavior, and agility training",
            "Good dogs start here",
            "Start Training",
            "/contact",
            2,
        ),
        sub(
            "boarding",
            "general",
            "pets",
            "Pet Boarding & Kennel",
            "\u{1F3E0}",
            "Overnight boarding and daycare",
            "A home away from home",
            "Reserve a Spot",
            "/book",
            3,
        ),
        // ── Childcare & Education ───────────────────────────────────────
        sub(
            "daycare",
            "general",
            "childcare",
            "Daycare / Childcare",
            "\u{1F476}",
            "Licensed childcare and preschool",
            "Nurturing minds, building futures",
            "Schedule a Tour",
            "/contact",
            1,
        ),
        sub(
            "tutoring",
            "general",
            "childcare",
            "Tutoring Center",
            "\u{1F4D6}",
            "Academic tutoring and test prep",
            "Every student can succeed",
            "Book a Session",
            "/book",
            2,
        ),
        sub(
            "after-school",
            "general",
            "childcare",
            "After-School Programs",
            "\u{1F3C3}",
            "Enrichment activities and homework help",
            "Learning doesn't stop at 3pm",
            "Enroll Now",
            "/contact",
            3,
        ),
        // ── Creative & Commerce ─────────────────────────────────────────
        sub(
            "print-shop",
            "general",
            "creative",
            "Print Shop",
            "\u{1F5A8}\u{FE0F}",
            "Business cards, banners, and custom printing",
            "Your vision, printed perfectly",
            "Get a Quote",
            "/contact",
            1,
        ),
        sub(
            "sign-shop",
            "general",
            "creative",
            "Sign Shop",
            "\u{1F3AC}",
            "Custom signs, vehicle wraps, and banners",
            "Signs that get noticed",
            "Request a Design",
            "/contact",
            2,
        ),
        sub(
            "screen-printing",
            "general",
            "creative",
            "Screen Printing & Embroidery",
            "\u{1F455}",
            "Custom apparel and promotional items",
            "Wear your brand",
            "Get a Quote",
            "/contact",
            3,
        ),
        sub(
            "art-gallery",
            "general",
            "creative",
            "Art Gallery",
            "\u{1F5BC}\u{FE0F}",
            "Art exhibitions and sales",
            "Discover original art",
            "Visit Us",
            "/",
            4,
        ),
        sub(
            "wedding-planner",
            "general",
            "creative",
            "Wedding Planner",
            "\u{1F490}",
            "Full-service wedding planning and coordination",
            "Your perfect day, perfectly planned",
            "Start Planning",
            "/contact",
            5,
        ),
        sub(
            "event-venue",
            "general",
            "creative",
            "Event Venue",
            "\u{1F3DB}\u{FE0F}",
            "Banquet halls, conference rooms, and event spaces",
            "The backdrop for your best moments",
            "Check Availability",
            "/book",
            6,
        ),
        // ── Additional Restaurants ──────────────────────────────────────
        sub(
            "bakery",
            "restaurant",
            "restaurants",
            "Bakery",
            "\u{1F35E}",
            "Fresh bread, pastries, and custom cakes",
            "Baked fresh daily",
            "Order Ahead",
            "/menu",
            11,
        ),
        sub(
            "coffee-shop",
            "restaurant",
            "restaurants",
            "Coffee Shop",
            "\u{2615}",
            "Specialty coffee, espresso, and cafe fare",
            "Your daily grind, elevated",
            "See Our Menu",
            "/menu",
            12,
        ),
        sub(
            "brewery-winery",
            "restaurant",
            "restaurants",
            "Brewery / Winery",
            "\u{1F37B}",
            "Craft beer, wine tasting, and taprooms",
            "Crafted with passion, poured with pride",
            "Visit Our Taproom",
            "/",
            13,
        ),
        sub(
            "sushi",
            "restaurant",
            "restaurants",
            "Sushi & Japanese",
            "\u{1F363}",
            "Sushi bar, ramen, and Japanese cuisine",
            "Fresh rolls, bold flavors",
            "See Our Menu",
            "/menu",
            14,
        ),
        // ── Additional Medical ──────────────────────────────────────────
        sub(
            "pharmacy",
            "medical",
            "medical",
            "Pharmacy",
            "\u{1F48A}",
            "Prescription filling, compounding, and wellness products",
            "Your neighborhood pharmacy",
            "Transfer Prescription",
            "/contact",
            10,
        ),
        sub(
            "orthodontist",
            "medical",
            "medical",
            "Orthodontist",
            "\u{1F601}",
            "Braces, Invisalign, and smile correction",
            "Straight teeth, confident smile",
            "Free Consultation",
            "/book",
            11,
        ),
        // ── Additional Beauty ───────────────────────────────────────────
        sub(
            "med-spa",
            "salon",
            "beauty",
            "Med Spa",
            "\u{1F489}",
            "Botox, fillers, laser treatments, and body contouring",
            "Science meets beauty",
            "Book Consultation",
            "/salon/book",
            8,
        ),
        sub(
            "tanning",
            "salon",
            "beauty",
            "Tanning Salon",
            "\u{2600}\u{FE0F}",
            "UV and spray tanning services",
            "Your glow, your way",
            "Book a Session",
            "/salon/book",
            9,
        ),
        // ── Additional Home Services ────────────────────────────────────
        sub(
            "window-cleaning",
            "general",
            "home-services",
            "Window Cleaning",
            "\u{1FA9F}",
            "Residential and commercial window cleaning",
            "Crystal-clear views",
            "Get a Quote",
            "/contact",
            12,
        ),
        sub(
            "pool-service",
            "general",
            "home-services",
            "Pool Service",
            "\u{1F3CA}",
            "Pool cleaning, maintenance, and repair",
            "Dive into a clean pool",
            "Schedule Service",
            "/book",
            13,
        ),
        sub(
            "junk-removal",
            "general",
            "home-services",
            "Junk Removal",
            "\u{267B}\u{FE0F}",
            "Residential and commercial junk hauling",
            "Gone today, not tomorrow",
            "Book a Pickup",
            "/book",
            14,
        ),
        // ── Additional Auto ─────────────────────────────────────────────
        sub(
            "transmission",
            "auto-repair",
            "auto",
            "Transmission Shop",
            "\u{2699}\u{FE0F}",
            "Transmission repair, rebuild, and replacement",
            "Shift with confidence",
            "Get a Diagnosis",
            "/contact",
            7,
        ),
        sub(
            "towing",
            "auto-repair",
            "auto",
            "Towing Service",
            "\u{1F69C}",
            "24/7 towing and roadside assistance",
            "Help is on the way",
            "Call for Tow",
            "/contact",
            8,
        ),
        // ── Additional Pest & Lawn ──────────────────────────────────────
        sub(
            "bed-bug",
            "pest-control",
            "pest-lawn",
            "Bed Bug Treatment",
            "\u{1F6CF}\u{FE0F}",
            "Bed bug detection, heat treatment, and prevention",
            "Sleep easy again",
            "Schedule Inspection",
            "/book",
            9,
        ),
        sub(
            "weed-control",
            "landscaping",
            "pest-lawn",
            "Weed Control & Fertilization",
            "\u{1F33E}",
            "Pre-emergent, post-emergent, and lawn fertilization programs",
            "A weed-free lawn, guaranteed",
            "Get a Quote",
            "/contact",
            10,
        ),
        // ── Additional Professional ─────────────────────────────────────
        sub(
            "financial-advisor",
            "general",
            "professional",
            "Financial Advisor",
            "\u{1F4B0}",
            "Retirement planning, investments, and wealth management",
            "Your financial future, secured",
            "Schedule Consultation",
            "/contact",
            6,
        ),
        sub(
            "marketing-agency",
            "general",
            "professional",
            "Marketing Agency",
            "\u{1F4E3}",
            "Digital marketing, SEO, and brand strategy",
            "Grow your brand, grow your business",
            "Get a Proposal",
            "/contact",
            7,
        ),

        // ── Community sub-specialties ──────────────────────────────────────
        // These extend the taxonomy beyond the original commerce-only design
        // so the wizard can ask "is this sports-team a little league or a
        // company league?" and tailor the homepage / nav / copy. Parent
        // slugs match the SiteTypeDefinition slug in defaults.rs.

        // Sports / scouts tiers
        sub("sports-team-little-league", "sports-team", "sports", "Little League / Youth", "\u{26BE}",
            "Youth recreational team — focus on practice, parent communication, and snacks rotation.",
            "Practice. Play. Have fun together.", "Practice Schedule", "/calendar", 80),
        sub("sports-team-high-school", "sports-team", "sports", "High School / Travel", "\u{1F3C6}",
            "Competitive school or club team — focus on game schedule, roster, recruiting, and recaps.",
            "Train hard. Play harder.", "Game Schedule", "/calendar", 81),
        sub("sports-team-minor-league", "sports-team", "sports", "Minor / Semi-Pro", "\u{1F3DF}\u{FE0F}",
            "Independent or minor-league club — ticket sales, merchandise, and standings matter.",
            "Buy tickets. Wear the gear.", "Tickets", "/products", 82),
        sub("sports-team-company-league", "sports-team", "sports", "Company / Corporate League", "\u{1F454}",
            "Workplace recreation team — schedule, RSVP, and gear orders.",
            "Work hard. Play together.", "RSVP", "/calendar", 83),
        sub("sports-team-military", "sports-team", "sports", "Military / Base Team", "\u{1F396}\u{FE0F}",
            "Base or unit recreation team — schedule, deployment-aware roster, and gear.",
            "On duty. On the field.", "Schedule", "/calendar", 84),
        sub("sports-team-church-team", "sports-team", "sports", "Church League", "\u{271D}\u{FE0F}",
            "Faith-based recreational league — schedule, parents night, and devotionals.",
            "Faith and fellowship on the field.", "Schedule", "/calendar", 85),

        // Family life-stage variants
        sub("family-young-kids", "family", "family", "Young Kids (0-5)", "\u{1F476}",
            "Family hub focused on baby/toddler routines, milestones, and nap schedules.",
            "Every little moment counts.", "Open the Site", "/feed", 90),
        sub("family-school-age", "family", "family", "School Age (6-12)", "\u{1F4DA}",
            "Homework, sports, chores, and the summer schedule — one place for the whole crew.",
            "Our family. One place. Always connected.", "Open the Site", "/feed", 91),
        sub("family-teens", "family", "family", "Teens at Home", "\u{1F484}",
            "Curfews, calendars, allowances, and the chore-vs-screen-time conversation.",
            "Stay close while they spread their wings.", "Open the Site", "/feed", 92),
        sub("family-multigen", "family", "family", "Multigenerational", "\u{1F46A}",
            "Grandparents, parents, kids — care notes, calendars, and shared memories under one roof.",
            "Every generation, one home.", "Open the Site", "/feed", 93),
        sub("family-empty-nest", "family", "family", "Empty Nest / Adult Kids", "\u{1F33F}",
            "Stay connected with adult kids and grandkids — birthdays, recipes, photos, calendars.",
            "Always near, even when they\u{2019}re far.", "Open the Site", "/feed", 94),

        // Church denominations / focus
        sub("church-baptist", "church", "faith", "Baptist Church", "\u{271D}\u{FE0F}",
            "Baptist congregation — sermons, ministries, missions, fellowship.",
            "Welcome home.", "Visit This Sunday", "/about", 100),
        sub("church-non-denom", "church", "faith", "Non-Denominational", "\u{1F49B}",
            "Modern non-denominational church — services, groups, giving, and a clear next step.",
            "Find your people.", "Visit This Sunday", "/about", 101),
        sub("church-catholic", "church", "faith", "Catholic Parish", "\u{26EA}",
            "Catholic parish — Mass schedule, sacraments, parish life.",
            "All are welcome.", "Mass Times", "/about", 102),
        sub("church-mission-focused", "church", "faith", "Mission-Focused", "\u{1F30D}",
            "Outward-facing church — mission trips, partner orgs, and community service.",
            "Faith in action.", "Get Involved", "/about", 103),

        // Classroom / education levels
        sub("classroom-elementary", "classroom", "education", "Elementary Class", "\u{270F}\u{FE0F}",
            "K\u{2013}5 classroom — weekly newsletter, homework, parent communication, photos.",
            "Learning together every day.", "This Week", "/calendar", 110),
        sub("classroom-middle-school", "classroom", "education", "Middle School Class", "\u{1F4D6}",
            "Grades 6\u{2013}8 classroom — assignments, agenda, after-school clubs.",
            "Building independence one assignment at a time.", "Assignments", "/calendar", 111),
        sub("classroom-high-school", "classroom", "education", "High School Class", "\u{1F393}",
            "High school classroom — syllabus, exam dates, college prep resources.",
            "Eyes on the next chapter.", "Syllabus", "/calendar", 112),

        // Band genres / context
        sub("band-indie", "band", "clubs", "Indie / Original Band", "\u{1F3B8}",
            "Independent original band — tour dates, releases, merch, mailing list.",
            "Music. Made by us. For you.", "Upcoming Shows", "/calendar", 120),
        sub("band-cover", "band", "clubs", "Cover / Wedding Band", "\u{1F3A4}",
            "Cover or wedding band — bookings, song list, video reel, contact.",
            "Hire the band that gets the dance floor full.", "Book Us", "/contact", 121),
        sub("band-school", "band", "clubs", "School / Marching Band", "\u{1F3BA}",
            "School band — practice schedule, performance dates, parent volunteer info.",
            "One band. One sound.", "Practice Schedule", "/calendar", 122),
        sub("band-worship", "band", "clubs", "Worship Team", "\u{1F64C}",
            "Church worship team — set lists, rehearsals, sound team rotation.",
            "Lead together every Sunday.", "Rehearsal Schedule", "/calendar", 123),
    ]
}

// ─── Lookup Helpers ─────────────────────────────────────────────────────────

/// Find all sub-specialties belonging to a given category slug.
pub fn subspecialties_by_category(category: &str) -> Vec<IndustrySubSpecialty> {
    all_subspecialties()
        .into_iter()
        .filter(|s| s.category == category)
        .collect()
}

/// Find all sub-specialties for a given parent industry slug.
pub fn subspecialties_by_industry(parent: &str) -> Vec<IndustrySubSpecialty> {
    all_subspecialties()
        .into_iter()
        .filter(|s| s.parent_industry == parent)
        .collect()
}

/// Look up a single sub-specialty by its slug.
pub fn find_subspecialty(slug: &str) -> Option<IndustrySubSpecialty> {
    all_subspecialties().into_iter().find(|s| s.slug == slug)
}

/// Look up a category by slug.
pub fn find_category(slug: &str) -> Option<IndustryCategory> {
    all_categories().into_iter().find(|c| c.slug == slug)
}

// ─── Constructor Helpers (private) ──────────────────────────────────────────

fn cat(slug: &str, name: &str, emoji: &str, desc: &str, order: u32) -> IndustryCategory {
    IndustryCategory {
        slug: slug.into(),
        name: name.into(),
        emoji: emoji.into(),
        description: desc.into(),
        display_order: order,
    }
}

fn sub(
    slug: &str,
    parent: &str,
    category: &str,
    name: &str,
    emoji: &str,
    desc: &str,
    tagline: &str,
    cta_text: &str,
    cta_url: &str,
    order: u32,
) -> IndustrySubSpecialty {
    IndustrySubSpecialty {
        slug: slug.into(),
        parent_industry: parent.into(),
        category: category.into(),
        name: name.into(),
        emoji: emoji.into(),
        description: desc.into(),
        tagline: tagline.into(),
        seo_title_suffix: name.into(),
        default_cta_text: cta_text.into(),
        default_cta_url: cta_url.into(),
        unique_nav_items: vec![],
        unique_pages: vec![],
        display_order: order,
    }
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn categories_have_unique_slugs() {
        let cats = all_categories();
        let mut slugs: Vec<&str> = cats.iter().map(|c| c.slug.as_str()).collect();
        let len = slugs.len();
        slugs.sort();
        slugs.dedup();
        assert_eq!(slugs.len(), len, "duplicate category slugs found");
    }

    #[test]
    fn subspecialties_have_unique_slugs() {
        let subs = all_subspecialties();
        let mut slugs: Vec<&str> = subs.iter().map(|s| s.slug.as_str()).collect();
        let len = slugs.len();
        slugs.sort();
        slugs.dedup();
        assert_eq!(slugs.len(), len, "duplicate sub-specialty slugs found");
    }

    #[test]
    fn all_subspecialties_reference_valid_categories() {
        let cats = all_categories();
        let cat_slugs: Vec<&str> = cats.iter().map(|c| c.slug.as_str()).collect();
        for sub in all_subspecialties() {
            assert!(
                cat_slugs.contains(&sub.category.as_str()),
                "sub-specialty '{}' references unknown category '{}'",
                sub.slug,
                sub.category
            );
        }
    }

    #[test]
    fn subspecialty_count_is_at_least_90() {
        let count = all_subspecialties().len();
        assert!(
            count >= 90,
            "expected at least 90 sub-specialties, got {count}"
        );
    }

    #[test]
    fn category_count_is_at_least_18() {
        let count = all_categories().len();
        assert!(count >= 18, "expected at least 18 categories, got {count}");
    }

    #[test]
    fn lookup_by_category_works() {
        let restaurant_subs = subspecialties_by_category("restaurants");
        assert!(
            restaurant_subs.len() >= 5,
            "expected at least 5 restaurant sub-specialties"
        );
        for s in &restaurant_subs {
            assert_eq!(s.category, "restaurants");
        }
    }

    #[test]
    fn lookup_by_industry_works() {
        let hvac_subs = subspecialties_by_industry("hvac");
        assert!(
            hvac_subs.len() >= 3,
            "expected at least 3 HVAC sub-specialties"
        );
        for s in &hvac_subs {
            assert_eq!(s.parent_industry, "hvac");
        }
    }

    #[test]
    fn find_subspecialty_works() {
        let result = find_subspecialty("food-truck");
        assert!(result.is_some());
        let ft = result.unwrap();
        assert_eq!(ft.name, "Food Truck");
        assert_eq!(ft.parent_industry, "restaurant");
    }

    #[test]
    fn find_category_works() {
        let result = find_category("auto");
        assert!(result.is_some());
        assert_eq!(result.unwrap().name, "Auto Services");
    }
}
